// Top-100 stub corpus for PL and NL. Direction flips bridge language.
// Initial state values are seeds; real state lives in the store after onboarding.

export const PL_WORDS = [
  { rank:1,  lemma:'być',       pos:'verb', nl:'zijn',           en:'to be',         seed:'known',      examples:['Jestem w domu.','On jest tutaj.'] },
  { rank:2,  lemma:'i',         pos:'conj', nl:'en',             en:'and',           seed:'known',      examples:['Mama i tata.'] },
  { rank:3,  lemma:'nie',       pos:'part', nl:'niet',           en:'not / no',      seed:'known',      examples:['To nie jest moje.'] },
  { rank:4,  lemma:'to',        pos:'pron', nl:'dit / dat',      en:'this / that',   seed:'known',      examples:['To jest dom.'] },
  { rank:5,  lemma:'się',       pos:'pron', nl:'zich',           en:'oneself',       seed:'recognized', examples:['Nazywam się Jeff.'] },
  { rank:6,  lemma:'na',        pos:'prep', nl:'op / naar',      en:'on / to',       seed:'known',      examples:['Na stole.','Idę na zakupy.'] },
  { rank:7,  lemma:'w',         pos:'prep', nl:'in',             en:'in',            seed:'known',      examples:['W Warszawie.'] },
  { rank:8,  lemma:'co',        pos:'pron', nl:'wat',            en:'what',          seed:'recognized', examples:['Co to jest?'] },
  { rank:9,  lemma:'jak',       pos:'adv',  nl:'hoe',            en:'how / as',      seed:'recognized', examples:['Jak się masz?'] },
  { rank:10, lemma:'ja',        pos:'pron', nl:'ik',             en:'I',             seed:'known',      examples:['Ja idę.'] },
  { rank:11, lemma:'ty',        pos:'pron', nl:'jij',            en:'you',           seed:'known',      examples:['Ty wiesz.'] },
  { rank:12, lemma:'mama',      pos:'noun', nl:'mama',           en:'mom',           seed:'known',      examples:['Mama je chleb.'] },
  { rank:13, lemma:'tak',       pos:'adv',  nl:'ja',             en:'yes / so',      seed:'recognized', examples:['Tak, oczywiście.'] },
  { rank:14, lemma:'mieć',      pos:'verb', nl:'hebben',         en:'to have',       seed:'recognized', examples:['Mam czas.'] },
  { rank:15, lemma:'że',        pos:'conj', nl:'dat',            en:'that',          seed:'heard',      examples:['Wiem, że to prawda.'] },
  { rank:16, lemma:'do',        pos:'prep', nl:'naar / tot',     en:'to / until',    seed:'recognized', examples:['Idę do sklepu.'] },
  { rank:17, lemma:'bardzo',    pos:'adv',  nl:'erg / heel',     en:'very',          seed:'recognized', examples:['Bardzo dziękuję.'] },
  { rank:18, lemma:'dom',       pos:'noun', nl:'huis',           en:'house / home',  seed:'recognized', examples:['Mój dom.'] },
  { rank:19, lemma:'dzień',     pos:'noun', nl:'dag',            en:'day',           seed:'recognized', examples:['Dobry dzień.'] },
  { rank:20, lemma:'dobry',     pos:'adj',  nl:'goed',           en:'good',          seed:'known',      examples:['Dobry wieczór.'] },
  { rank:21, lemma:'wiedzieć',  pos:'verb', nl:'weten',          en:'to know',       seed:'heard',      examples:['Wiem to.'] },
  { rank:22, lemma:'tu',        pos:'adv',  nl:'hier',           en:'here',          seed:'recognized', examples:['Jestem tu.'] },
  { rank:23, lemma:'tam',       pos:'adv',  nl:'daar',           en:'there',         seed:'heard',      examples:['Tam jest.'] },
  { rank:24, lemma:'tylko',     pos:'adv',  nl:'alleen / slechts',en:'only',         seed:'heard',      examples:['Tylko ja.'] },
  { rank:25, lemma:'dziecko',   pos:'noun', nl:'kind',           en:'child',         seed:'heard',      examples:['Małe dziecko.'] },
  { rank:26, lemma:'rok',       pos:'noun', nl:'jaar',           en:'year',          seed:'heard',      examples:['Mam dziesięć lat.'] },
  { rank:27, lemma:'człowiek',  pos:'noun', nl:'mens',           en:'human / person',seed:'heard',      examples:['Dobry człowiek.'] },
  { rank:28, lemma:'powiedzieć',pos:'verb', nl:'zeggen',         en:'to say',        seed:'heard',      examples:['Powiedział to.'] },
  { rank:29, lemma:'czas',      pos:'noun', nl:'tijd',           en:'time',          seed:'recognized', examples:['Mam czas.'] },
  { rank:30, lemma:'pan',       pos:'noun', nl:'meneer',         en:'sir / Mr.',     seed:'heard',      examples:['Pan Kowalski.'] },
  { rank:31, lemma:'może',      pos:'adv',  nl:'misschien',      en:'maybe',         seed:'heard',      examples:['Może jutro.'] },
  { rank:32, lemma:'bo',        pos:'conj', nl:'omdat',          en:'because',       seed:'heard',      examples:['Bo tak chcę.'] },
  { rank:33, lemma:'jeszcze',   pos:'adv',  nl:'nog',            en:'still / yet',   seed:'new',        examples:['Jeszcze nie.'] },
  { rank:34, lemma:'już',       pos:'adv',  nl:'al',             en:'already',       seed:'recognized', examples:['Już idę.'] },
  { rank:35, lemma:'jeden',     pos:'num',  nl:'één',            en:'one',           seed:'known',      examples:['Jeden raz.'] },
  { rank:36, lemma:'kobieta',   pos:'noun', nl:'vrouw',          en:'woman',         seed:'heard',      examples:['Młoda kobieta.'] },
  { rank:37, lemma:'mężczyzna', pos:'noun', nl:'man',            en:'man',           seed:'new',        examples:['Wysoki mężczyzna.'] },
  { rank:38, lemma:'praca',     pos:'noun', nl:'werk',           en:'work / job',    seed:'heard',      examples:['Idę do pracy.'] },
  { rank:39, lemma:'gdzie',     pos:'adv',  nl:'waar',           en:'where',         seed:'recognized', examples:['Gdzie jesteś?'] },
  { rank:40, lemma:'dać',       pos:'verb', nl:'geven',          en:'to give',       seed:'new',        examples:['Daj mi to.'] },
  { rank:41, lemma:'kiedy',     pos:'adv',  nl:'wanneer',        en:'when',          seed:'new',        examples:['Kiedy przyjdziesz?'] },
  { rank:42, lemma:'chleb',     pos:'noun', nl:'brood',          en:'bread',         seed:'recognized', examples:['Świeży chleb.'] },
  { rank:43, lemma:'woda',      pos:'noun', nl:'water',          en:'water',         seed:'recognized', examples:['Szklanka wody.'] },
  { rank:44, lemma:'tata',      pos:'noun', nl:'papa',           en:'dad',           seed:'known',      examples:['Tata pracuje.'] },
  { rank:45, lemma:'jeść',      pos:'verb', nl:'eten',           en:'to eat',        seed:'recognized', examples:['Mama je chleb.'] },
  { rank:46, lemma:'pić',       pos:'verb', nl:'drinken',        en:'to drink',      seed:'heard',      examples:['Piję wodę.'] },
  { rank:47, lemma:'iść',       pos:'verb', nl:'gaan',           en:'to go',         seed:'heard',      examples:['Idę do domu.'] },
  { rank:48, lemma:'duży',      pos:'adj',  nl:'groot',          en:'big',           seed:'new',        examples:['Duży dom.'] },
  { rank:49, lemma:'mały',      pos:'adj',  nl:'klein',          en:'small',         seed:'new',        examples:['Małe dziecko.'] },
  { rank:50, lemma:'ulica',     pos:'noun', nl:'straat',         en:'street',        seed:'new',        examples:['Główna ulica.'] },
  { rank:51, lemma:'pociąg',    pos:'noun', nl:'trein',          en:'train',         seed:'new',        examples:['Pociąg do Krakowa.'] },
  { rank:52, lemma:'kawa',      pos:'noun', nl:'koffie',         en:'coffee',        seed:'recognized', examples:['Czarna kawa.'] },
  { rank:53, lemma:'herbata',   pos:'noun', nl:'thee',           en:'tea',           seed:'heard',      examples:['Gorąca herbata.'] },
  { rank:54, lemma:'cześć',     pos:'intj', nl:'hoi',            en:'hi',            seed:'known',      examples:['Cześć, Halina!'] },
  { rank:55, lemma:'dziękuję',  pos:'intj', nl:'dank je',        en:'thank you',     seed:'known',      examples:['Bardzo dziękuję.'] },
  { rank:56, lemma:'proszę',    pos:'intj', nl:'alsjeblieft',    en:'please / here', seed:'known',      examples:['Proszę bardzo.'] },
  { rank:57, lemma:'przepraszam',pos:'intj',nl:'sorry',          en:'excuse me',     seed:'recognized', examples:['Przepraszam, pani.'] },
  { rank:58, lemma:'rano',      pos:'adv',  nl:"'s ochtends",    en:'morning',       seed:'new',        examples:['Wcześnie rano.'] },
  { rank:59, lemma:'wieczór',   pos:'noun', nl:'avond',          en:'evening',       seed:'new',        examples:['Dobry wieczór.'] },
  { rank:60, lemma:'noc',       pos:'noun', nl:'nacht',          en:'night',         seed:'new',        examples:['Dobranoc.'] },
  { rank:61, lemma:'ojciec',    pos:'noun', nl:'vader',          en:'father',        seed:'new',        examples:['Mój ojciec.'] },
  { rank:62, lemma:'matka',     pos:'noun', nl:'moeder',         en:'mother',        seed:'new',        examples:['Moja matka.'] },
  { rank:63, lemma:'syn',       pos:'noun', nl:'zoon',           en:'son',           seed:'new',        examples:['Mój syn.'] },
  { rank:64, lemma:'córka',     pos:'noun', nl:'dochter',        en:'daughter',      seed:'new',        examples:['Moja córka.'] },
  { rank:65, lemma:'brat',      pos:'noun', nl:'broer',          en:'brother',       seed:'new',        examples:['Mój brat.'] },
  { rank:66, lemma:'siostra',   pos:'noun', nl:'zus',            en:'sister',        seed:'new',        examples:['Moja siostra.'] },
  { rank:67, lemma:'przyjaciel',pos:'noun', nl:'vriend',         en:'friend',        seed:'new',        examples:['Dobry przyjaciel.'] },
  { rank:68, lemma:'książka',   pos:'noun', nl:'boek',           en:'book',          seed:'new',        examples:['Ciekawa książka.'] },
  { rank:69, lemma:'film',      pos:'noun', nl:'film',           en:'film',          seed:'recognized', examples:['Dobry film.'] },
  { rank:70, lemma:'muzyka',    pos:'noun', nl:'muziek',         en:'music',         seed:'recognized', examples:['Cicha muzyka.'] },
  { rank:71, lemma:'samochód',  pos:'noun', nl:'auto',           en:'car',           seed:'new',        examples:['Mój samochód.'] },
  { rank:72, lemma:'sklep',     pos:'noun', nl:'winkel',         en:'shop',          seed:'new',        examples:['Idę do sklepu.'] },
  { rank:73, lemma:'szkoła',    pos:'noun', nl:'school',         en:'school',        seed:'new',        examples:['Idę do szkoły.'] },
  { rank:74, lemma:'pracować',  pos:'verb', nl:'werken',         en:'to work',       seed:'heard',      examples:['Pracuję w domu.'] },
  { rank:75, lemma:'czytać',    pos:'verb', nl:'lezen',          en:'to read',       seed:'new',        examples:['Czytam książkę.'] },
  { rank:76, lemma:'pisać',     pos:'verb', nl:'schrijven',      en:'to write',      seed:'new',        examples:['Piszę list.'] },
  { rank:77, lemma:'mówić',     pos:'verb', nl:'spreken',        en:'to speak',      seed:'heard',      examples:['Mówię po polsku.'] },
  { rank:78, lemma:'rozumieć',  pos:'verb', nl:'begrijpen',      en:'to understand', seed:'new',        examples:['Rozumiem to.'] },
  { rank:79, lemma:'kupować',   pos:'verb', nl:'kopen',          en:'to buy',        seed:'new',        examples:['Kupuję chleb.'] },
  { rank:80, lemma:'lubić',     pos:'verb', nl:'leuk vinden',    en:'to like',       seed:'recognized', examples:['Lubię kawę.'] },
  { rank:81, lemma:'kochać',    pos:'verb', nl:'liefhebben',     en:'to love',       seed:'recognized', examples:['Kocham cię.'] },
  { rank:82, lemma:'myśleć',    pos:'verb', nl:'denken',         en:'to think',      seed:'heard',      examples:['Myślę, że tak.'] },
  { rank:83, lemma:'czekać',    pos:'verb', nl:'wachten',        en:'to wait',       seed:'new',        examples:['Czekam na ciebie.'] },
  { rank:84, lemma:'przyjść',   pos:'verb', nl:'komen',          en:'to come',       seed:'new',        examples:['Przyjdę jutro.'] },
  { rank:85, lemma:'wyjść',     pos:'verb', nl:'uitgaan',        en:'to go out',     seed:'new',        examples:['Wychodzę z domu.'] },
  { rank:86, lemma:'spać',      pos:'verb', nl:'slapen',         en:'to sleep',      seed:'new',        examples:['Śpię osiem godzin.'] },
  { rank:87, lemma:'wstać',     pos:'verb', nl:'opstaan',        en:'to get up',     seed:'new',        examples:['Wstaję rano.'] },
  { rank:88, lemma:'stół',      pos:'noun', nl:'tafel',          en:'table',         seed:'new',        examples:['Na stole.'] },
  { rank:89, lemma:'krzesło',   pos:'noun', nl:'stoel',          en:'chair',         seed:'new',        examples:['Drewniane krzesło.'] },
  { rank:90, lemma:'okno',      pos:'noun', nl:'raam',           en:'window',        seed:'new',        examples:['Otwarte okno.'] },
  { rank:91, lemma:'drzwi',     pos:'noun', nl:'deur',           en:'door',          seed:'new',        examples:['Zamknij drzwi.'] },
  { rank:92, lemma:'ulubiony',  pos:'adj',  nl:'favoriet',       en:'favourite',     seed:'new',        examples:['Mój ulubiony film.'] },
  { rank:93, lemma:'nowy',      pos:'adj',  nl:'nieuw',          en:'new',           seed:'recognized', examples:['Nowy dom.'] },
  { rank:94, lemma:'stary',     pos:'adj',  nl:'oud',            en:'old',           seed:'recognized', examples:['Stary samochód.'] },
  { rank:95, lemma:'piękny',    pos:'adj',  nl:'mooi',           en:'beautiful',     seed:'heard',      examples:['Piękny dzień.'] },
  { rank:96, lemma:'szczęśliwy',pos:'adj',  nl:'gelukkig',       en:'happy',         seed:'new',        examples:['Szczęśliwy człowiek.'] },
  { rank:97, lemma:'smutny',    pos:'adj',  nl:'verdrietig',     en:'sad',           seed:'new',        examples:['Smutna piosenka.'] },
  { rank:98, lemma:'szybki',    pos:'adj',  nl:'snel',           en:'fast',          seed:'new',        examples:['Szybki pociąg.'] },
  { rank:99, lemma:'wolny',     pos:'adj',  nl:'langzaam / vrij',en:'slow / free',   seed:'new',        examples:['Wolny dzień.'] },
  { rank:100,lemma:'cały',      pos:'adj',  nl:'heel',           en:'whole',         seed:'new',        examples:['Cały dzień.'] },
];

export const NL_WORDS = [
  { rank:1,  lemma:'de',        pos:'art', pl:'(rodzajnik)',  en:'the',           seed:'known',      examples:['De man is hier.'] },
  { rank:2,  lemma:'en',        pos:'conj',pl:'i',            en:'and',           seed:'known',      examples:['Mama en papa.'] },
  { rank:3,  lemma:'van',       pos:'prep',pl:'od / z',       en:'of / from',     seed:'known',      examples:['Het huis van mijn moeder.'] },
  { rank:4,  lemma:'het',       pos:'art', pl:'(rodzajnik)',  en:'the / it',      seed:'known',      examples:['Het is goed.'] },
  { rank:5,  lemma:'een',       pos:'art', pl:'jeden / pewien',en:'a / one',      seed:'known',      examples:['Een appel.'] },
  { rank:6,  lemma:'in',        pos:'prep',pl:'w',            en:'in',            seed:'known',      examples:['In Amsterdam.'] },
  { rank:7,  lemma:'is',        pos:'verb',pl:'jest',         en:'is',            seed:'known',      examples:['Hij is hier.'] },
  { rank:8,  lemma:'dat',       pos:'pron',pl:'że / tamten',  en:'that',          seed:'recognized', examples:['Ik weet dat.'] },
  { rank:9,  lemma:'op',        pos:'prep',pl:'na',           en:'on',            seed:'known',      examples:['Op de tafel.'] },
  { rank:10, lemma:'te',        pos:'part',pl:'do / aby',     en:'to / too',      seed:'recognized', examples:['Ik ga te voet.'] },
  { rank:11, lemma:'zijn',      pos:'verb',pl:'być',          en:'to be / his',   seed:'known',      examples:['Wij zijn thuis.'] },
  { rank:12, lemma:'mama',      pos:'noun',pl:'mama',         en:'mom',           seed:'known',      examples:['Mama eet brood.'] },
  { rank:13, lemma:'niet',      pos:'adv', pl:'nie',          en:'not',           seed:'known',      examples:['Dat is niet goed.'] },
  { rank:14, lemma:'voor',      pos:'prep',pl:'przed / dla',  en:'for / before',  seed:'recognized', examples:['Voor jou.'] },
  { rank:15, lemma:'met',       pos:'prep',pl:'z',            en:'with',          seed:'known',      examples:['Met mijn vriend.'] },
  { rank:16, lemma:'hebben',    pos:'verb',pl:'mieć',         en:'to have',       seed:'recognized', examples:['Ik heb tijd.'] },
  { rank:17, lemma:'aan',       pos:'prep',pl:'do / na',      en:'on / to',       seed:'recognized', examples:['Aan de tafel.'] },
  { rank:18, lemma:'maar',      pos:'conj',pl:'ale',          en:'but',           seed:'recognized', examples:['Klein maar fijn.'] },
  { rank:19, lemma:'huis',      pos:'noun',pl:'dom',          en:'house',         seed:'recognized', examples:['Mijn huis.'] },
  { rank:20, lemma:'goed',      pos:'adj', pl:'dobry',        en:'good',          seed:'known',      examples:['Goed gedaan.'] },
  { rank:21, lemma:'weten',     pos:'verb',pl:'wiedzieć',     en:'to know',       seed:'heard',      examples:['Ik weet het.'] },
  { rank:22, lemma:'hier',      pos:'adv', pl:'tu',           en:'here',          seed:'recognized', examples:['Hier ben ik.'] },
  { rank:23, lemma:'daar',      pos:'adv', pl:'tam',          en:'there',         seed:'heard',      examples:['Daar is het.'] },
  { rank:24, lemma:'alleen',    pos:'adv', pl:'tylko / sam',  en:'only / alone',  seed:'heard',      examples:['Alleen ik.'] },
  { rank:25, lemma:'kind',      pos:'noun',pl:'dziecko',      en:'child',         seed:'heard',      examples:['Een klein kind.'] },
  { rank:26, lemma:'jaar',      pos:'noun',pl:'rok',          en:'year',          seed:'heard',      examples:['Tien jaar oud.'] },
  { rank:27, lemma:'mens',      pos:'noun',pl:'człowiek',     en:'human / person',seed:'heard',      examples:['Een goed mens.'] },
  { rank:28, lemma:'zeggen',    pos:'verb',pl:'powiedzieć',   en:'to say',        seed:'heard',      examples:['Hij zei het.'] },
  { rank:29, lemma:'tijd',      pos:'noun',pl:'czas',         en:'time',          seed:'recognized', examples:['Ik heb tijd.'] },
  { rank:30, lemma:'meneer',    pos:'noun',pl:'pan',          en:'sir',           seed:'heard',      examples:['Meneer Jansen.'] },
  { rank:31, lemma:'misschien', pos:'adv', pl:'może',         en:'maybe',         seed:'heard',      examples:['Misschien morgen.'] },
  { rank:32, lemma:'omdat',     pos:'conj',pl:'bo',           en:'because',       seed:'heard',      examples:['Omdat ik wil.'] },
  { rank:33, lemma:'nog',       pos:'adv', pl:'jeszcze',      en:'still / yet',   seed:'new',        examples:['Nog niet.'] },
  { rank:34, lemma:'al',        pos:'adv', pl:'już',          en:'already',       seed:'recognized', examples:['Ik ga al.'] },
  { rank:35, lemma:'één',       pos:'num', pl:'jeden',        en:'one',           seed:'known',      examples:['Eén keer.'] },
  { rank:36, lemma:'vrouw',     pos:'noun',pl:'kobieta',      en:'woman',         seed:'heard',      examples:['Een jonge vrouw.'] },
  { rank:37, lemma:'man',       pos:'noun',pl:'mężczyzna',    en:'man',           seed:'new',        examples:['Een lange man.'] },
  { rank:38, lemma:'werk',      pos:'noun',pl:'praca',        en:'work',          seed:'heard',      examples:['Ik ga naar werk.'] },
  { rank:39, lemma:'waar',      pos:'adv', pl:'gdzie',        en:'where',         seed:'recognized', examples:['Waar ben je?'] },
  { rank:40, lemma:'geven',     pos:'verb',pl:'dać',          en:'to give',       seed:'new',        examples:['Geef het maar.'] },
  { rank:41, lemma:'wanneer',   pos:'adv', pl:'kiedy',        en:'when',          seed:'new',        examples:['Wanneer kom je?'] },
  { rank:42, lemma:'brood',     pos:'noun',pl:'chleb',        en:'bread',         seed:'recognized', examples:['Vers brood.'] },
  { rank:43, lemma:'water',     pos:'noun',pl:'woda',         en:'water',         seed:'recognized', examples:['Een glas water.'] },
  { rank:44, lemma:'papa',      pos:'noun',pl:'tata',         en:'dad',           seed:'known',      examples:['Papa werkt.'] },
  { rank:45, lemma:'eten',      pos:'verb',pl:'jeść',         en:'to eat',        seed:'recognized', examples:['Mama eet brood.'] },
  { rank:46, lemma:'drinken',   pos:'verb',pl:'pić',          en:'to drink',      seed:'heard',      examples:['Ik drink water.'] },
  { rank:47, lemma:'gaan',      pos:'verb',pl:'iść',          en:'to go',         seed:'heard',      examples:['Ik ga naar huis.'] },
  { rank:48, lemma:'groot',     pos:'adj', pl:'duży',         en:'big',           seed:'new',        examples:['Een groot huis.'] },
  { rank:49, lemma:'klein',     pos:'adj', pl:'mały',         en:'small',         seed:'new',        examples:['Een klein kind.'] },
  { rank:50, lemma:'straat',    pos:'noun',pl:'ulica',        en:'street',        seed:'new',        examples:['De hoofdstraat.'] },
  { rank:51, lemma:'trein',     pos:'noun',pl:'pociąg',       en:'train',         seed:'new',        examples:['De trein naar Utrecht.'] },
  { rank:52, lemma:'koffie',    pos:'noun',pl:'kawa',         en:'coffee',        seed:'recognized', examples:['Zwarte koffie.'] },
  { rank:53, lemma:'thee',      pos:'noun',pl:'herbata',      en:'tea',           seed:'heard',      examples:['Hete thee.'] },
  { rank:54, lemma:'hoi',       pos:'intj',pl:'cześć',        en:'hi',            seed:'known',      examples:['Hoi, Halina!'] },
  { rank:55, lemma:'dank je',   pos:'intj',pl:'dziękuję',     en:'thank you',     seed:'known',      examples:['Heel erg dank je.'] },
  { rank:56, lemma:'alsjeblieft',pos:'intj',pl:'proszę',      en:'please',        seed:'known',      examples:['Alsjeblieft.'] },
  { rank:57, lemma:'sorry',     pos:'intj',pl:'przepraszam',  en:'sorry',         seed:'recognized', examples:['Sorry, mevrouw.'] },
  { rank:58, lemma:"'s ochtends",pos:'adv',pl:'rano',         en:'in the morning',seed:'new',        examples:["Vroeg 's ochtends."] },
  { rank:59, lemma:'avond',     pos:'noun',pl:'wieczór',      en:'evening',       seed:'new',        examples:['Goedenavond.'] },
  { rank:60, lemma:'nacht',     pos:'noun',pl:'noc',          en:'night',         seed:'new',        examples:['Goede nacht.'] },
  { rank:61, lemma:'vader',     pos:'noun',pl:'ojciec',       en:'father',        seed:'new',        examples:['Mijn vader.'] },
  { rank:62, lemma:'moeder',    pos:'noun',pl:'matka',        en:'mother',        seed:'new',        examples:['Mijn moeder.'] },
  { rank:63, lemma:'zoon',      pos:'noun',pl:'syn',          en:'son',           seed:'new',        examples:['Mijn zoon.'] },
  { rank:64, lemma:'dochter',   pos:'noun',pl:'córka',        en:'daughter',      seed:'new',        examples:['Mijn dochter.'] },
  { rank:65, lemma:'broer',     pos:'noun',pl:'brat',         en:'brother',       seed:'new',        examples:['Mijn broer.'] },
  { rank:66, lemma:'zus',       pos:'noun',pl:'siostra',      en:'sister',        seed:'new',        examples:['Mijn zus.'] },
  { rank:67, lemma:'vriend',    pos:'noun',pl:'przyjaciel',   en:'friend',        seed:'new',        examples:['Mijn vriend.'] },
  { rank:68, lemma:'boek',      pos:'noun',pl:'książka',      en:'book',          seed:'new',        examples:['Een interessant boek.'] },
  { rank:69, lemma:'film',      pos:'noun',pl:'film',         en:'film',          seed:'recognized', examples:['Een goede film.'] },
  { rank:70, lemma:'muziek',    pos:'noun',pl:'muzyka',       en:'music',         seed:'recognized', examples:['Stille muziek.'] },
  { rank:71, lemma:'auto',      pos:'noun',pl:'samochód',     en:'car',           seed:'new',        examples:['Mijn auto.'] },
  { rank:72, lemma:'winkel',    pos:'noun',pl:'sklep',        en:'shop',          seed:'new',        examples:['Naar de winkel.'] },
  { rank:73, lemma:'school',    pos:'noun',pl:'szkoła',       en:'school',        seed:'new',        examples:['Naar school.'] },
  { rank:74, lemma:'werken',    pos:'verb',pl:'pracować',     en:'to work',       seed:'heard',      examples:['Ik werk thuis.'] },
  { rank:75, lemma:'lezen',     pos:'verb',pl:'czytać',       en:'to read',       seed:'new',        examples:['Ik lees een boek.'] },
  { rank:76, lemma:'schrijven', pos:'verb',pl:'pisać',        en:'to write',      seed:'new',        examples:['Ik schrijf een brief.'] },
  { rank:77, lemma:'spreken',   pos:'verb',pl:'mówić',        en:'to speak',      seed:'heard',      examples:['Ik spreek Nederlands.'] },
  { rank:78, lemma:'begrijpen', pos:'verb',pl:'rozumieć',     en:'to understand', seed:'new',        examples:['Ik begrijp het.'] },
  { rank:79, lemma:'kopen',     pos:'verb',pl:'kupować',      en:'to buy',        seed:'new',        examples:['Ik koop brood.'] },
  { rank:80, lemma:'leuk vinden',pos:'verb',pl:'lubić',       en:'to like',       seed:'recognized', examples:['Ik vind koffie leuk.'] },
  { rank:81, lemma:'liefhebben',pos:'verb',pl:'kochać',       en:'to love',       seed:'recognized', examples:['Ik hou van jou.'] },
  { rank:82, lemma:'denken',    pos:'verb',pl:'myśleć',       en:'to think',      seed:'heard',      examples:['Ik denk van wel.'] },
  { rank:83, lemma:'wachten',   pos:'verb',pl:'czekać',       en:'to wait',       seed:'new',        examples:['Ik wacht op jou.'] },
  { rank:84, lemma:'komen',     pos:'verb',pl:'przyjść',      en:'to come',       seed:'new',        examples:['Ik kom morgen.'] },
  { rank:85, lemma:'uitgaan',   pos:'verb',pl:'wyjść',        en:'to go out',     seed:'new',        examples:['Ik ga uit.'] },
  { rank:86, lemma:'slapen',    pos:'verb',pl:'spać',         en:'to sleep',      seed:'new',        examples:['Ik slaap acht uur.'] },
  { rank:87, lemma:'opstaan',   pos:'verb',pl:'wstać',        en:'to get up',     seed:'new',        examples:['Ik sta vroeg op.'] },
  { rank:88, lemma:'tafel',     pos:'noun',pl:'stół',         en:'table',         seed:'new',        examples:['Op de tafel.'] },
  { rank:89, lemma:'stoel',     pos:'noun',pl:'krzesło',      en:'chair',         seed:'new',        examples:['Een houten stoel.'] },
  { rank:90, lemma:'raam',      pos:'noun',pl:'okno',         en:'window',        seed:'new',        examples:['Een open raam.'] },
  { rank:91, lemma:'deur',      pos:'noun',pl:'drzwi',        en:'door',          seed:'new',        examples:['Doe de deur dicht.'] },
  { rank:92, lemma:'favoriet',  pos:'adj', pl:'ulubiony',     en:'favourite',     seed:'new',        examples:['Mijn favoriete film.'] },
  { rank:93, lemma:'nieuw',     pos:'adj', pl:'nowy',         en:'new',           seed:'recognized', examples:['Een nieuw huis.'] },
  { rank:94, lemma:'oud',       pos:'adj', pl:'stary',        en:'old',           seed:'recognized', examples:['Een oude auto.'] },
  { rank:95, lemma:'mooi',      pos:'adj', pl:'piękny',       en:'beautiful',     seed:'heard',      examples:['Een mooie dag.'] },
  { rank:96, lemma:'gelukkig',  pos:'adj', pl:'szczęśliwy',   en:'happy',         seed:'new',        examples:['Een gelukkig mens.'] },
  { rank:97, lemma:'verdrietig',pos:'adj', pl:'smutny',       en:'sad',           seed:'new',        examples:['Een verdrietig lied.'] },
  { rank:98, lemma:'snel',      pos:'adj', pl:'szybki',       en:'fast',          seed:'new',        examples:['Een snelle trein.'] },
  { rank:99, lemma:'langzaam',  pos:'adj', pl:'wolny',        en:'slow',          seed:'new',        examples:['Een langzame dag.'] },
  { rank:100,lemma:'heel',      pos:'adj', pl:'cały',         en:'whole',         seed:'new',        examples:['De hele dag.'] },
];

export const STATE_ORDER = ['new', 'heard', 'recognized', 'known'];
export const STATE_LABEL = { new: 'New', heard: 'Heard', recognized: 'Recognized', known: 'Known' };

// Inflected forms — direction-agnostic, only PL has interesting inflection for the v1.
export const FORMS_PL = {
  'być':        [{ form: 'jestem',  hint: 'ja' }, { form: 'jesteś',   hint: 'ty' },     { form: 'jest',     hint: 'on/ona' }],
  'mieć':       [{ form: 'mam',     hint: 'ja' }, { form: 'masz',     hint: 'ty' },     { form: 'ma',       hint: 'on/ona' }],
  'wiedzieć':   [{ form: 'wiem',    hint: 'ja' }, { form: 'wiesz',    hint: 'ty' },     { form: 'wiedział', hint: 'past m.' }],
  'powiedzieć': [{ form: 'powiem',  hint: 'ja' }, { form: 'powiesz',  hint: 'ty' },     { form: 'powiedział', hint: 'past m.' }],
  'jeść':       [{ form: 'jem',     hint: 'ja' }, { form: 'jesz',     hint: 'ty' },     { form: 'je',       hint: 'on/ona' }],
  'pić':        [{ form: 'piję',    hint: 'ja' }, { form: 'pijesz',   hint: 'ty' },     { form: 'pije',     hint: 'on/ona' }],
  'iść':        [{ form: 'idę',     hint: 'ja' }, { form: 'idziesz',  hint: 'ty' },     { form: 'idzie',    hint: 'on/ona' }],
  'dać':        [{ form: 'daję',    hint: 'ja' }, { form: 'dajesz',   hint: 'ty' },     { form: 'daj',      hint: 'imp.' }],
  'ja':         [{ form: 'mnie',    hint: 'gen/acc' }, { form: 'mi',   hint: 'dat' },   { form: 'mną',      hint: 'instr.' }],
  'ty':         [{ form: 'cię',     hint: 'acc' },     { form: 'tobie',hint: 'dat/loc' },{ form: 'tobą',    hint: 'instr.' }],
  'pan':        [{ form: 'pana',    hint: 'gen/acc' }, { form: 'panu', hint: 'dat' },   { form: 'panie',    hint: 'voc.' }],
  'się':        [{ form: 'siebie',  hint: 'gen/acc' }, { form: 'sobie',hint: 'dat/loc' },{ form: 'sobą',    hint: 'instr.' }],
  'to':         [{ form: 'tego',    hint: 'gen' },     { form: 'temu', hint: 'dat' },   { form: 'tym',      hint: 'instr/loc' }],
  'co':         [{ form: 'czego',   hint: 'gen' },     { form: 'czemu',hint: 'dat' },   { form: 'czym',     hint: 'instr/loc' }],
  'dom':        [{ form: 'domu',    hint: 'gen/loc' }, { form: 'domem',hint: 'instr.' },{ form: 'domy',     hint: 'plural' }],
  'dzień':      [{ form: 'dnia',    hint: 'gen' },     { form: 'dni',  hint: 'plural' },{ form: 'dniem',    hint: 'instr.' }],
  'dziecko':    [{ form: 'dziecka', hint: 'gen' },     { form: 'dziecku',hint: 'dat' }, { form: 'dzieci',   hint: 'plural' }],
  'rok':        [{ form: 'roku',    hint: 'gen/loc' }, { form: 'lat',  hint: 'pl gen' },{ form: 'lata',     hint: 'plural' }],
  'człowiek':   [{ form: 'człowieka',hint: 'gen/acc' },{ form: 'ludzie',hint: 'plural' },{ form: 'ludzi',   hint: 'pl gen' }],
  'czas':       [{ form: 'czasu',   hint: 'gen' },     { form: 'czasem',hint: 'instr.' },{ form: 'czasy',   hint: 'plural' }],
  'kobieta':    [{ form: 'kobiety', hint: 'gen' },     { form: 'kobiecie',hint: 'dat/loc' },{ form: 'kobietą',hint: 'instr.' }],
  'mężczyzna':  [{ form: 'mężczyzny',hint: 'gen' },    { form: 'mężczyźnie',hint: 'loc' },{ form: 'mężczyźni',hint: 'plural' }],
  'praca':      [{ form: 'pracy',   hint: 'gen/dat' }, { form: 'pracą',hint: 'instr.' },{ form: 'prace',    hint: 'plural' }],
  'mama':       [{ form: 'mamy',    hint: 'gen' },     { form: 'mamie',hint: 'dat/loc' },{ form: 'mamą',    hint: 'instr.' }],
  'tata':       [{ form: 'taty',    hint: 'gen' },     { form: 'tacie',hint: 'dat/loc' },{ form: 'tatą',    hint: 'instr.' }],
  'chleb':      [{ form: 'chleba',  hint: 'gen' },     { form: 'chlebem',hint: 'instr.' },{ form: 'chlebie',hint: 'loc' }],
  'woda':       [{ form: 'wody',    hint: 'gen' },     { form: 'wodzie',hint: 'dat/loc' },{ form: 'wodą',   hint: 'instr.' }],
  'kawa':       [{ form: 'kawy',    hint: 'gen' },     { form: 'kawie',hint: 'dat/loc' },{ form: 'kawą',    hint: 'instr.' }],
  'herbata':    [{ form: 'herbaty', hint: 'gen' },     { form: 'herbacie',hint: 'dat/loc' },{ form: 'herbatą',hint: 'instr.' }],
  'ulica':      [{ form: 'ulicy',   hint: 'gen/dat' }, { form: 'ulicą',hint: 'instr.' },{ form: 'ulice',    hint: 'plural' }],
  'pociąg':     [{ form: 'pociągu', hint: 'gen' },     { form: 'pociągiem',hint: 'instr.' },{ form: 'pociągi',hint: 'plural' }],
  'wieczór':    [{ form: 'wieczoru',hint: 'gen' },     { form: 'wieczorem',hint: 'instr.' },{ form: 'wieczory',hint: 'plural' }],
  'noc':        [{ form: 'nocy',    hint: 'gen' },     { form: 'nocą', hint: 'instr.' },{ form: 'nocach',   hint: 'pl loc' }],
  'dobry':      [{ form: 'dobra',   hint: 'fem.' },    { form: 'dobre',hint: 'neut.' },  { form: 'dobrze',   hint: 'adv.' }],
  'duży':       [{ form: 'duża',    hint: 'fem.' },    { form: 'duże', hint: 'neut.' },  { form: 'dużo',     hint: 'adv.' }],
  'mały':       [{ form: 'mała',    hint: 'fem.' },    { form: 'małe', hint: 'neut.' },  { form: 'mało',     hint: 'adv.' }],
  'jeden':      [{ form: 'jedna',   hint: 'fem.' },    { form: 'jedno',hint: 'neut.' },  { form: 'jednego',  hint: 'gen.' }],
  'nowy':       [{ form: 'nowa',    hint: 'fem.' },    { form: 'nowe', hint: 'neut.' },  { form: 'nowi',     hint: 'pl m.' }],
  'stary':      [{ form: 'stara',   hint: 'fem.' },    { form: 'stare',hint: 'neut.' },  { form: 'starzy',   hint: 'pl m.' }],
  'piękny':     [{ form: 'piękna',  hint: 'fem.' },    { form: 'piękne',hint: 'neut.' }, { form: 'pięknie',  hint: 'adv.' }],
};

export function wordsFor(dir) {
  return dir === 'nl-from-pl' ? NL_WORDS : PL_WORDS;
}
export function bridgeOf(w, dir) {
  if (dir === 'pl-from-nl') return w.nl;
  if (dir === 'nl-from-pl') return w.pl;
  return w.en;
}
export function formsFor(lemma, dir) {
  if (dir !== 'pl-from-nl') return null;
  return FORMS_PL[lemma] || null;
}
