#!/usr/bin/env python3
"""Build the offline 1,000-word corpora from FrequencyWords/OpenSubtitles."""
import json, re, time
from pathlib import Path
from urllib.parse import urlencode
from urllib.request import urlopen
import morfeusz2

ROOT = Path(__file__).resolve().parents[1]
URL = 'https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/{lang}/{lang}_50k.txt'
LANGS = ('pl', 'en', 'nl')

def fetch(lang):
    with urlopen(URL.format(lang=lang)) as r:
        lines = r.read().decode('utf-8').splitlines()
    words=[]
    for line in lines:
        word, count = line.rsplit(' ', 1)
        if re.fullmatch(r"[\wÀ-žąćęłńóśźżĄĆĘŁŃÓŚŹŻ'-]+", word, re.UNICODE):
            words.append((word, int(count)))
        if len(words)==1000: break
    return words

def translate(words, source):
    if source == 'en': return words
    out=[]
    for start in range(0, len(words), 50):
        batch=words[start:start+50]
        params=urlencode({'client':'gtx','sl':source,'tl':'en','dt':'t','q':'\n'.join(batch)})
        with urlopen('https://translate.googleapis.com/translate_a/single?'+params) as r:
            payload=json.load(r)
        text=''.join(part[0] for part in payload[0]).strip('\n')
        translated=text.split('\n')
        if len(translated)!=len(batch): translated=['']*len(batch)
        out.extend(translated)
        time.sleep(.04)
    return out

def hint(tag):
    bits=tag.split(':')
    labels={'sg':'singular','pl':'plural','nom':'nominative','gen':'genitive','dat':'dative',
      'acc':'accusative','inst':'instrumental','loc':'locative','voc':'vocative','pri':'I/we',
      'sec':'you','ter':'he/she/they','praet':'past','fin':'present','impt':'imperative',
      'inf':'infinitive','cond':'conditional','m1':'masc. personal','m2':'masculine','m3':'masculine',
      'f':'feminine','n':'neuter'}
    found=[]
    for b in bits:
        for atom in b.split('.'):
            if atom in labels and labels[atom] not in found: found.append(labels[atom])
    return ' · '.join(found[:3]) or bits[0]

def polish_info(word, morph):
    analyses=morph.analyse(word)
    if not analyses: return ('word', word, [])
    interp=analyses[0][2]
    lemma=interp[1].split(':')[0]
    tag=interp[2]
    kind=tag.split(':')[0]
    pos={'subst':'noun','depr':'noun','ger':'noun','fin':'verb','inf':'verb','praet':'verb',
      'impt':'verb','imps':'verb','bedzie':'verb','winien':'verb','pact':'verb','ppas':'verb',
      'adj':'adjective','adja':'adjective','adjp':'adjective','adv':'adverb','prep':'preposition',
      'conj':'conjunction','comp':'conjunction','num':'number','ppron12':'pronoun','ppron3':'pronoun',
      'siebie':'pronoun','pred':'particle','qub':'particle','interj':'interjection'}.get(kind,'word')
    generated=morph.generate(lemma)
    unique=[]; seen={word}
    # Prefer useful finite/case forms and keep the payload compact.
    preferred=('nom','gen','dat','acc','inst','loc','voc','fin','praet','impt','bedzie')
    generated.sort(key=lambda x: (not any(p in x[2].split(':') for p in preferred), len(x[0])))
    for form, _, ftag, *_ in generated:
        if form.lower() in seen or not re.fullmatch(r"[\wąćęłńóśźżĄĆĘŁŃÓŚŹŻ'-]+", form): continue
        seen.add(form.lower()); unique.append({'form':form,'hint':hint(ftag)})
        if len(unique)==8: break
    return pos, lemma, unique

def main():
    morph=morfeusz2.Morfeusz(generate=True)
    all_data={}
    for lang in LANGS:
        rows=fetch(lang); words=[w for w,_ in rows]; translations=translate(words,lang)
        entries=[]
        for rank, ((word,count), english) in enumerate(zip(rows,translations),1):
            if lang=='pl': rawpos, base, forms=polish_info(word,morph)
            else: rawpos, base, forms='word',word,[]
            entries.append({'rank':rank,'lemma':word,'base':base,'pos':rawpos,'en':english or word,
              'frequency':count,'forms':forms})
        all_data[lang]=entries
    out='// Generated by scripts/build-frequency-data.py. Do not edit by hand.\n'
    out+='// Source: FrequencyWords (OpenSubtitles 2018), CC BY-SA 4.0.\n'
    for lang in LANGS:
        out+=f'export const {lang.upper()}_WORDS = '+json.dumps(all_data[lang],ensure_ascii=False,separators=(',',':'))+';\n'
    (ROOT/'js/generated/frequency-data.js').write_text(out,encoding='utf-8')

if __name__=='__main__': main()
